-- MySQL Script generated by MySQL Workbench
-- Sat Jul 25 14:31:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ita-model-bbdd-ex6
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ita-model-bbdd-ex6
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ita-model-bbdd-ex6` DEFAULT CHARACTER SET utf8 ;
USE `ita-model-bbdd-ex6` ;

-- -----------------------------------------------------
-- Table `ita-model-bbdd-ex6`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ita-model-bbdd-ex6`.`Supplier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `streetNumber` INT NOT NULL,
  `floor` INT NOT NULL,
  `door` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `postalCode` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ita-model-bbdd-ex6`.`Mark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ita-model-bbdd-ex6`.`Mark` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `supplierId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Mark_Supplier_idx` (`supplierId` ASC) VISIBLE,
  CONSTRAINT `fk_Mark_Supplier`
    FOREIGN KEY (`supplierId`)
    REFERENCES `ita-model-bbdd-ex6`.`Supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ita-model-bbdd-ex6`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ita-model-bbdd-ex6`.`Glasses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `markId` INT NOT NULL,
  `gradeLeft` VARCHAR(45) NOT NULL,
  `gradeRight` VARCHAR(45) NOT NULL,
  `frameType` ENUM('Flotant', 'Pasta', 'Metàl·lica') NOT NULL,
  `frameColor` VARCHAR(45) NOT NULL,
  `leftColor` VARCHAR(45) NOT NULL,
  `rightColor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Glasses_Mark1_idx` (`markId` ASC) VISIBLE,
  CONSTRAINT `fk_Glasses_Mark1`
    FOREIGN KEY (`markId`)
    REFERENCES `ita-model-bbdd-ex6`.`Mark` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ita-model-bbdd-ex6`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ita-model-bbdd-ex6`.`Customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `registeredOn` DATETIME NOT NULL DEFAULT NOW(),
  `recommendedByCustomerId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Customer_Customer1_idx` (`recommendedByCustomerId` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Customer1`
    FOREIGN KEY (`recommendedByCustomerId`)
    REFERENCES `ita-model-bbdd-ex6`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ita-model-bbdd-ex6`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ita-model-bbdd-ex6`.`Employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ita-model-bbdd-ex6`.`Sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ita-model-bbdd-ex6`.`Sale` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `glassesId` INT NOT NULL,
  `customerId` INT NOT NULL,
  `employeeId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Sale_Glasses1_idx` (`glassesId` ASC) VISIBLE,
  INDEX `fk_Sale_Customer1_idx` (`customerId` ASC) VISIBLE,
  INDEX `fk_Sale_Employee1_idx` (`employeeId` ASC) VISIBLE,
  CONSTRAINT `fk_Sale_Glasses1`
    FOREIGN KEY (`glassesId`)
    REFERENCES `ita-model-bbdd-ex6`.`Glasses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sale_Customer1`
    FOREIGN KEY (`customerId`)
    REFERENCES `ita-model-bbdd-ex6`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sale_Employee1`
    FOREIGN KEY (`employeeId`)
    REFERENCES `ita-model-bbdd-ex6`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
