-- MySQL Script generated by MySQL Workbench
-- Tue Jul 21 20:11:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ita-model-bbdd-ex2
-- -----------------------------------------------------
-- Exercici 2 de modelatge de BBDD per accés a IT Academy

-- -----------------------------------------------------
-- Schema ita-model-bbdd-ex2
--
-- Exercici 2 de modelatge de BBDD per accés a IT Academy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ita-model-bbdd-ex2` DEFAULT CHARACTER SET utf8 ;
USE `ita-model-bbdd-ex2` ;

-- -----------------------------------------------------
-- Table `ita-model-bbdd-ex2`.`Painting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ita-model-bbdd-ex2`.`Painting` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` DOUBLE NULL,
  `author` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ita-model-bbdd-ex2`.`Buyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ita-model-bbdd-ex2`.`Buyer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ita-model-bbdd-ex2`.`Sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ita-model-bbdd-ex2`.`Sale` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `buyerId` INT NOT NULL,
  `paintingId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_VENTA_COMPRADOR_idx` (`buyerId` ASC) VISIBLE,
  INDEX `fk_VENTA_QUADRES1_idx` (`paintingId` ASC) VISIBLE,
  CONSTRAINT `fk_VENTA_COMPRADOR`
    FOREIGN KEY (`buyerId`)
    REFERENCES `ita-model-bbdd-ex2`.`Buyer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENTA_QUADRES1`
    FOREIGN KEY (`paintingId`)
    REFERENCES `ita-model-bbdd-ex2`.`Painting` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
