-- MySQL Script generated by MySQL Workbench
-- Tue Jul 21 21:46:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ita-model-bbdd-ex3
-- -----------------------------------------------------
-- Exercici 3 de modelatge de BBDD per a l’accès a IT Academy: Stube

-- -----------------------------------------------------
-- Schema ita-model-bbdd-ex3
--
-- Exercici 3 de modelatge de BBDD per a l’accès a IT Academy: Stube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ita-model-bbdd-ex3` DEFAULT CHARACTER SET utf8 ;
USE `ita-model-bbdd-ex3` ;

-- -----------------------------------------------------
-- Table `ita-model-bbdd-ex3`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ita-model-bbdd-ex3`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ita-model-bbdd-ex3`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ita-model-bbdd-ex3`.`Video` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `url` VARCHAR(45) NOT NULL,
  `videoId` VARCHAR(45) NOT NULL,
  `userId` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `videoId_UNIQUE` (`videoId` ASC) VISIBLE,
  INDEX `fk_Videos_User_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_Videos_User`
    FOREIGN KEY (`userId`)
    REFERENCES `ita-model-bbdd-ex3`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
