-- MySQL Script generated by MySQL Workbench
-- Thu Jul 23 20:25:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ita-model-bbdd-ex5
-- -----------------------------------------------------
-- Exercici 5 Accès IT Academy

-- -----------------------------------------------------
-- Schema ita-model-bbdd-ex5
--
-- Exercici 5 Accès IT Academy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ita-model-bbdd-ex5` DEFAULT CHARACTER SET utf8 ;
USE `ita-model-bbdd-ex5` ;

-- -----------------------------------------------------
-- Table `ita-model-bbdd-ex5`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ita-model-bbdd-ex5`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ita-model-bbdd-ex5`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ita-model-bbdd-ex5`.`Photo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) VISIBLE,
  INDEX `fk_Photo_User1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_Photo_User1`
    FOREIGN KEY (`userId`)
    REFERENCES `ita-model-bbdd-ex5`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ita-model-bbdd-ex5`.`Friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ita-model-bbdd-ex5`.`Friend` (
  `howMeet` VARCHAR(45) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `friendId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Friend_User2_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_Friend_User1_idx` (`friendId` ASC) VISIBLE,
  CONSTRAINT `fk_Friend_User2`
    FOREIGN KEY (`userId`)
    REFERENCES `ita-model-bbdd-ex5`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Friend_User1`
    FOREIGN KEY (`friendId`)
    REFERENCES `ita-model-bbdd-ex5`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
